name: prayer_schedule_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  adhan: ^2.0.0+1
  date_picker_plus: ^4.1.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  geolocator: ^10.0.0
  intl: ^0.20.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/background_images/
    - assets/images/
    - assets/icons/

  fonts:
    - family: kanit
      fonts:
        - asset: assets/fonts/Kanit/Kanit-Regular.ttf
